name: DaanDesign
favicon: null
layout_spectrum: 0.5574206698220223
typography_spectrum: 0.2834159545600414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.18270022957585752
  saturation: 0.2061876873485744
  rhythmicContrast: 0.5
purpose: []
